In [1]:
import numpy as np
 
A = np.zeros((75, 5), dtype=float)  # 先创建一个全零方阵A，并且数据的类型设置为float浮点型
 
f = open('F:\\Code\\Mode Regonization\\Iris\\test.txt')  # 打开数据文件文件
lines = f.readlines()  # 把全部数据文件读到一个列表lines中
A_row = 0  # 表示矩阵的行，从0行开始
for line in lines:  # 把lines中的数据逐行读取出来
    list = line.strip('\n').split('\t')  # 处理逐行数据：strip表示把头尾的'\n'去掉，split表示以空格来分割行数据，然后把处理后的行数据返回到list列表中
    A[A_row:] = list[0:5]  # 把处理后的数据放到方阵A中。list[0:4]表示列表的0,1,2,3列数据放到矩阵A中的A_row行
    A_row += 1  # 然后方阵A的下一行接着读
print(A.round(1)) # 保留一位小数输出

[[1.  5.  3.  1.6 0.2]
 [1.  5.  3.4 1.6 0.4]
 [1.  5.2 3.5 1.5 0.2]
 [1.  5.2 3.4 1.4 0.2]
 [1.  4.7 3.2 1.6 0.2]
 [1.  4.8 3.1 1.6 0.2]
 [1.  5.4 3.4 1.5 0.4]
 [1.  5.2 4.1 1.5 0.1]
 [1.  5.5 4.2 1.4 0.2]
 [1.  4.9 3.1 1.5 0.2]
 [1.  5.  3.2 1.2 0.2]
 [1.  5.5 3.5 1.3 0.2]
 [1.  4.9 3.6 1.4 0.1]
 [1.  4.4 3.  1.3 0.2]
 [1.  5.1 3.4 1.5 0.2]
 [1.  5.  3.5 1.3 0.3]
 [1.  4.5 2.3 1.3 0.3]
 [1.  4.4 3.2 1.3 0.2]
 [1.  5.  3.5 1.6 0.6]
 [1.  5.1 3.8 1.9 0.4]
 [1.  4.8 3.  1.4 0.3]
 [1.  5.1 3.8 1.6 0.2]
 [1.  4.6 3.2 1.4 0.2]
 [1.  5.3 3.7 1.5 0.2]
 [1.  5.  3.3 1.4 0.2]
 [2.  6.6 3.  4.4 1.4]
 [2.  6.8 2.8 4.8 1.4]
 [2.  6.7 3.  5.  1.7]
 [2.  6.  2.9 4.5 1.5]
 [2.  5.7 2.6 3.5 1. ]
 [2.  5.5 2.4 3.8 1.1]
 [2.  5.5 2.4 3.7 1. ]
 [2.  5.8 2.7 3.9 1.2]
 [2.  6.  2.7 5.1 1.6]
 [2.  5.4 3.  4.5 1.5]
 [2.  6.  3.4 4.5 1.6]
 [2.  6.7 3.1 4.7 1.5]
 [2.  6.3 2.3 4.4 1.3]
 [2.  5.6 3.  4.1 1.3]
 [2.  5.5 2.5 4.  1.3]
 [2.  5.5 2.6 4.4 1.2]
 [2.  6.1 3.  4.6 1.4]
 [2.  5.8 2.6 4.  1.2]
 [2.  5.  2

In [2]:
A1 = A[0:25]
print(A1)

[[1.  5.  3.  1.6 0.2]
 [1.  5.  3.4 1.6 0.4]
 [1.  5.2 3.5 1.5 0.2]
 [1.  5.2 3.4 1.4 0.2]
 [1.  4.7 3.2 1.6 0.2]
 [1.  4.8 3.1 1.6 0.2]
 [1.  5.4 3.4 1.5 0.4]
 [1.  5.2 4.1 1.5 0.1]
 [1.  5.5 4.2 1.4 0.2]
 [1.  4.9 3.1 1.5 0.2]
 [1.  5.  3.2 1.2 0.2]
 [1.  5.5 3.5 1.3 0.2]
 [1.  4.9 3.6 1.4 0.1]
 [1.  4.4 3.  1.3 0.2]
 [1.  5.1 3.4 1.5 0.2]
 [1.  5.  3.5 1.3 0.3]
 [1.  4.5 2.3 1.3 0.3]
 [1.  4.4 3.2 1.3 0.2]
 [1.  5.  3.5 1.6 0.6]
 [1.  5.1 3.8 1.9 0.4]
 [1.  4.8 3.  1.4 0.3]
 [1.  5.1 3.8 1.6 0.2]
 [1.  4.6 3.2 1.4 0.2]
 [1.  5.3 3.7 1.5 0.2]
 [1.  5.  3.3 1.4 0.2]]


In [4]:
mean1 = np.average(A1, axis=0)  # 按列求均值
print(mean1)

[1.    4.984 3.376 1.464 0.244]


In [8]:
from scipy.linalg import expm,logm
y = np.ones((2,2))
x = expm(y)
print(x)
print(y)

[[4.19452805 3.19452805]
 [3.19452805 4.19452805]]
[[1. 1.]
 [1. 1.]]
